[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "privacy-policy-analyzer"
version = "0.1.0"
description = "Tools to crawl, analyze and report on website privacy policies using NLP models and rule-based patterns."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["privacy", "nlp", "crawler", "privacy-policy", "classification"]
requires-python = ">=3.12"
dependencies = [
    # ML/Analysis
    "torch",
    "transformers",
    "datasets",
    "huggingface-hub",
    "numpy",
    "accelerate",
    "bitsandbytes",
    "scikit-learn",
    "protobuf",
    "sentencepiece",

    # Crawler
    "beautifulsoup4",
    "playwright",
    "requests",
    "html5lib",
    "langdetect",

    # Visualization
    "matplotlib",
    "pandas",
]


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
