from privacy_policy_analyzer.analysis.attributes import (
    AttributePattern,
    AttributePatterns,
    DatePattern,
    DurationPattern,
)
from privacy_policy_analyzer.crawl.splitter import SplitterPattern

# ------------------------------------------------------------------------------------------

EN_SPLITTER_CONFIG: SplitterPattern = SplitterPattern.from_parts(
    replace_words=[
        ("e\\. g\\.", "e.g."),
        ("i\\. e\\.", "i.e."),
        ("e\\. g\\,", "e.g,"),
        ("U\\. S\\.", "USA"),
        ("U\\.S\\.", "USA"),
        ("U\\.S\\.A\\.", "USA"),
        ("U\\. K\\.", "UK"),
        ("U\\.K\\.", "UK"),
    ],
    last_on_line=[
        "\\.$",
        "\\!$",
        "\\?$",
    ],
    not_last_on_line=[
        "^[0-9]+\\.$",
        "^[A-Za-z]\\.$",
        "^[VIX]{1,4}\\.$",
        "e\\.g\\.$",
        "i\\.e\\.$",
        "Mr\\.$",
        "Mrs\\.$",
        "Dr\\.$",
        "Prof\\.$",
        "Inc\\.$",
        "Ltd\\.$",
        "Jr\\.$",
        "Sr\\.$",
        "vs\\.$",
        "etc\\.$",
        "Fig\\.$",
        "fig\\.$",
        "St\\.$",
        "Co\\.$",
        "Corp\\.$",
        "Mt\\.$",
        "Rd\\.$",
        "Ln\\.$",
        "Blvd\\.$",
        "Art\\.$",
        "para\\.$",
        "lit\\.$",
        "^[A-Z]\\.[A-Z]\\.$",
    ],
    first_on_newline=["^·$", "^•$", "^●$", "^\\*$", "^o$"],
    not_first_on_newline=[],
    sentence_not_split_pattern=[
        "para\\. [0-9]\\. s\\.$",
        "Art\\. [0-9] para\\.\\s*[0-9] s\\.$",
        "Art\\. [0-9] para\\. [0-9]\\.( s\\.)?$",
        "Art\\. [0-9] para\\. s\\.$",
    ],
)
""" English language splitter configuration. """


# ------------------------------------------------------------------------------------------

EN_PATTERN_CONFIG: AttributePatterns = AttributePatterns(
    data_type=AttributePattern.from_dict(
        {
            "PersonalData": [
                "(?<!non-)(?<!sensitive )(?<!special categories of )personal(.){0,20}(data|information|detail)"
            ],
            "SensitiveData": ["sensitive(.){0,20}(data|information|detail)"],
            "SpecialCategoryData": [
                "special category (data|information|detail)",
                "special categories of personal data",
            ],
            "GeneralInformation": [
                "general(.){0,20}(data|information)(?! Protection Regulation)"
            ],
            "PII": [
                "PII",
                "(?<!non-)personally identifiable information",
                "information(.){0,20}personally identifies",
                "(data|information)(.){0,30}(?!does not)(?!don(.)t)identify you personally",
                "information that directly identifies you",
            ],
            "NPII": [
                "non-personally identifiable information",
                "non-personal(.){0,20}information",
            ],
            "SetupInformation": ["setup information"],
            "DeviceInformation": [
                "device(.){0,16}(information|data)",
                "(information|data)(.){0,20}about(.){0,20}(device|product)",
            ],
            "DeviceName": [
                "(device|product) name",
                "name of (device|product)",
                "camera name",
            ],
            "DeviceType": [
                "(device|product) (type|model)",
                "(type|model) of (device|product)",
                "phone model",
                "hardware (model|type)",
                "device(.){0,20}\\bmodel\\b",
            ],
            "ManufacturerInformation": [
                "manufacturer (information|data|detail)",
                "(information|detail(s)?) about(.){0,20}manufacturer",
            ],
            "TechnicalInformation": ["technical (information|data)"],
            "OperatingSystem": ["operating system"],
            "FirmwareVersion": ["firmware version"],
            "HardwareInformation": [
                "hardware (information|data|details)",
                "information (about|on)(.){0,20}(hardware)",
            ],
            "HardwareVersion": ["hardware version"],
            "BrowserInformation": [
                "browser (information|data)",
                "information (about|on)(.){0,20}(browser)",
            ],
            "BrowserType": ["browser(.){0,20}type", "type of browser"],
            "BrowserVersion": ["browser(.){0,20}version", "version of browser"],
            "AppVersion": ["app version"],
            "ActivationTime": ["activation time", "activation date"],
            "PartnerApp": ["partner app", "third(-| )party app"],
            "InternetServiceProvider": ["internet service provider", "\\bISP\\b"],
            "NetworkData": [
                "(?<!media )network(.){0,20}(data|information)",
                "network activity",
            ],
            "CustomerProprietaryNetworkInformation": [
                "customer proprietary network information",
                "\\bCPNI\\b",
            ],
            "OtherElectronicNetworkActivityInformation": [
                "other electronic network activity information",
                "\\bOENAI\\b",
            ],
            "MobileNetworkData": ["mobile network(.){0,20}(data|information)"],
            "MobileNetworkCode": ["mobile network code"],
            "MobileCountryCode": ["mobile country code"],
            "ConnectionData": ["connection(.){0,20}(data|information)"],
            "DataAmount": ["data amount", "amount of data", "network bandwidth usage"],
            "WiFiData": [
                "Wi(-)?Fi (data|information)",
                "information about(.){0,20}wi(-)?fi",
            ],
            "WiFiStatus": ["Wi(-)?Fi (status|state)"],
            "WiFiHeatmap": ["Wi(-)?Fi heat( )?map", "wi(-)?fi signal map"],
            "SSID": ["SSID", "wi(-)?fi(.){0,20}name", "network name", "wi(-)?fi id"],
            "SignalStrength": ["signal strength", "connectivity stability"],
            "InternetSpeed": ["internet speed", "network speed"],
            "UsageData": [
                "usage(.){0,20}(data|information|behavior)",
                "(?<!network )usage statistics",
                "usage of (feature|service|product)",
                "(your|user(s')?) behavior",
                "(device|product|app|site) usage",
                "actions of(.){0,20}(user|you|visitor|customer)",
                "track(.){0,20}usage",
                "(?<!network )activity(.){0,20}(data|information)",
                "(?<!network )activity statistics",
                "(your|user) interaction(s)?",
                "how (you|user(s)?|visitor(s)?) (interact|use|access|engage)",
                "information about (your|user) activity",
                "interaction (data|information)",
                "your activities",
                "usage (trend|pattern)",
                "interaction pattern",
            ],
            "UsageDuration": [
                "usage duration",
                "duration of(.){0,20}(use|usage|visit)",
                "how long you use",
                "time(.){0,20}spen(t|d)",
                "length of visit",
                "access duration",
            ],
            "TelemetryData": ["telemetry (data|information)"],
            "PerformanceData": [
                "(?<!conversion )performance(.){0,20}(data|information|metric)"
            ],
            "DiagnosticData": ["diagnostic(.){0,20}(data|information)"],
            "StatisticalData": ["statistical (data|information)"],
            "DeviceStatistics": ["device stat(s|istics)"],
            "DeviceInteractions": ["device interaction"],
            "SettingsData": ["settings"],
            "UserPreferences": ["(user|your) preference", "preferences"],
            "FontSize": ["font size"],
            "DeviceState": ["device (state|status)"],
            "OnlineStatus": ["online status"],
            "BatteryData": ["battery (data|information|status|level|life)"],
            "MemoryUsage": ["memory usage", "RAM usage"],
            "StorageUsage": [
                "(storage|disk) (usage|utilization)",
                "storage capacity used",
            ],
            "CpuUsage": ["(CPU|processor) (usage|utilization)"],
            "ScreenUnlocks": [
                "screen unlock(s)?",
                "device unlock(s)?",
                "number of unlocks",
                "number of times(.){0,20}screen(.){0,20}(unlocked|woken)",
            ],
            "UsageFrequency": [
                "usage frequency",
                "how often you use",
                "frequency of(.){0,20}(use|usage)",
                "how frequently you use",
            ],
            "BrowsingActivity": ["browsing (activity|data|information|history)"],
            "ViewedContent": [
                "viewed content",
                "content you(.){0,20}(viewed|accessed|watched)",
            ],
            "VisitedPages": [
                "visited page",
                "page(s)?(.){0,20}(visited|viewed|accessed)",
                "page visit",
            ],
            "ClickedLinks": ["clicked link", "link(.){0,20}click"],
            "MouseMovements": [
                "mouse movement",
                "mouse activity",
                "mouse tracking",
                "mouse-over",
            ],
            "Keystrokes": ["keystroke", "key press", "keyboard input"],
            "SearchHistory": ["search history", "searched terms", "search queries"],
            "PageInteractions": [
                "page interaction",
                "website interaction",
                "site interaction",
            ],
            "LogData": ["log (data|information)", "\\btechnical logs\\b"],
            "LogFiles": ["log file"],
            "DeviceLogs": ["device log"],
            "Errors": [
                "(crash|error)(.){0,20}(data|information|report|event|message|log|details)",
                "\\bcrashes\\b",
                "\\berror(s)?\\b",
            ],
            "AccessLogs": [
                "access log",
                "access report",
                "access message",
                "security log",
            ],
            "ActivityLogs": ["activity log"],
            "MaintenanceLogs": ["maintenance log", "maintenance record"],
            "DrivingEvents": ["driving event"],
            "DeviceEvents": ["device event"],
            "DateTime": [
                "(?<!up to )\\bdate\\b",
                "(?<!to )(?<!real-)(?<!from )(?<!every )(?<!any )(?<!each )\\btime\\b",
            ],
            "MACAddress": ["MAC address", "mac-address"],
            "IPAddress": ["IP address", "ip-address", "\\(IP\\) address"],
            "SerialNumber": ["serial number"],
            "DeviceTemperature": [
                "(device|product) temperature",
                "temperature of (device|product)",
            ],
            "ScheduleTimes": ["schedule(.){0,20}time"],
            "Identifier": [
                "identification number",
                "personal identifier",
                "\\bidentifier(s)?\\b",
                "unique identifier",
                "unique ID",
            ],
            "AccountID": ["account ID", "account identifier"],
            "DeviceID": [
                "device(-| )ID",
                "device identifier",
                "unique device ID",
                "UDID",
                "device number",
            ],
            "AdvertisingID": ["advertising ID", "advertising identifier", "IDFA"],
            "SessionID": ["session ID", "session identifier"],
            "UserID": ["user ID", "user identifier"],
            "OpenID": ["open( |-)ID", "open identifier", "\\bO(A)?ID\\b"],
            "GoogleAdID": ["Google (ad|advertising) ID", "GAID"],
            "WindowsAdID": ["Windows (ad|advertising) ID"],
            "AndroidID": ["Android ID", "\\bAAID\\b"],
            "FCMToken": ["FCM token", "Firebase Cloud Messaging token"],
            "SpaceID": ["space( |-)ID"],
            "ClickID": ["click ID", "click identifier"],
            "ICCID": ["ICCID", "Integrated Circuit Card Identifier"],
            "IMEI": ["IMEI", "International Mobile Equipment Identity"],
            "IMSI": ["IMSI", "International Mobile Subscriber Identity"],
            "SIMInformation": ["SIM(.){0,20}(data|information)"],
            "Referrer": ["referrer", "referring(.){0,20}(URL|website)", "referer"],
            "HostName": ["host name", "hostname"],
            "URL": ["URL", "uniform resource locator", "hyperlink"],
            "Clicks": ["clicks", "click data"],
            "ScrollData": ["scroll data", "\\bscroll(s)?\\b"],
            "Clickstream": ["click( )?stream"],
            "PageResponseTime": ["page response time", "website response time"],
            "ScreenResolution": ["screen resolution", "display resolution"],
            "LocationData": ["(?<!in )location"],
            "LocationHistory": ["location history"],
            "GPSData": ["GPS (data|information)"],
            "Coordinates": ["coordinates", "latitude", "longitude"],
            "AltitudeData": ["\\baltitude\\b", "elevation data"],
            "Timezone": ["time zone"],
            "Address": [
                "(?<!email[\\s-])(?<!e-mail[\\s-])(?<!ip[\\s-])(?<!\\(ip\\)[\\s-])address"
            ],
            "AreaCode": ["area code", "zip code", "postal code", "postcode"],
            "City": ["\\bcity\\b"],
            "Country": ["(?<!outside of your )(?<!to the )country"],
            "Language": ["language"],
            "Name": [
                "(?<!device )(?<!home )(?<!product )(?<!first)(?<!last)(?<!nick)(?<!user)name\\b(?!:)(?! of the)",
                "full name",
            ],
            "FirstName": ["first name", "given name"],
            "LastName": ["last name", "surname", "family name"],
            "Nickname": ["nickname", "nick name"],
            "DemographicData": ["demographic(.){0,20}(data|information)"],
            "LifestyleInformation": ["lifestyle(.){0,20}(information|data)"],
            "NumberOfChildren": ["number of children", "children count"],
            "PetInformation": [
                "pet (information|data)",
                "information about(.){0,20}pet",
            ],
            "NumberOfPets": ["number of pet", "pet count"],
            "Age": ["\\bage\\b"],
            "DateOfBirth": ["date of birth", "birth date", "birthday"],
            "PhysicalBodyMetrics": ["physical body(.){0,20}(metric|measurement)"],
            "Height": ["\\bheight\\b"],
            "Weight": ["\\bweight\\b"],
            "Gender": ["\\bgender\\b"],
            "Nationality": ["\\bnationality\\b", "\\bcitizenship\\b"],
            "SexualOrientation": ["sexual orientation", "sexual preference"],
            "SexualLife": ["\\bsexual life\\b", "\\bsexual activity\\b"],
            "BiographicInformation": ["biographic (information|data)"],
            "EducationalBackground": [
                "educational(.){0,20}background",
                "education level",
                "prior education",
            ],
            "EmploymentBackground": [
                "employment(.){0,20}background",
                "job title",
                "occupation",
                "work history",
            ],
            "Employer": [
                "\\bemployer\\b",
                "company you work for",
                "organization you work for",
            ],
            "Ethnicity": ["ethnicity", "\\brace\\b"],
            "PoliticalAffiliations": [
                "political (affiliation|view|belief|party|opinion)\\b"
            ],
            "ReligiousBeliefs": ["religious (belief|view|affiliation)\\b"],
            "CriminalOffenses": [
                "criminal offense(s)?",
                "criminal record",
                "criminal history",
            ],
            "TradeUnionMembership": ["\\btrade union (membership|affiliation)"],
            "SocialAssistanceData": ["\\bsocial assistance\\b"],
            "ContactInformation": ["contact (information|info|data|details)"],
            "EmailAddress": [
                "email address",
                "(?<!by )(?<!to )(?<!send you )(?<!via )e(-)?mail(?! protected)",
            ],
            "PhoneNumber": ["phone number", "telephone number", "mobile number"],
            "EmergencyData": ["emergency(.){0,20}(contact|information|data)"],
            "FamilyInformation": [
                "family(.){0,20}(information|data|details)",
                "information about(.){0,20}family",
                "family member(s)?",
                "family relationship",
            ],
            "FriendsInformation": [
                "friend(s)?(.){0,20}(information|data)",
                "information about(.){0,20}friend",
            ],
            "GovernmentID": [
                "government ID",
                "government issued ID",
                "government identification",
                "official identification",
            ],
            "Passport": ["\\bpassport\\b"],
            "DriverLicense": [
                "driver(.)?s license",
                "driving license",
                "driver license number",
            ],
            "TaxID": [
                "tax ID",
                "tax identification number",
                "taxpayer identification number",
            ],
            "SocialSecurityNumber": ["social security number", "\\bSSN\\b"],
            "AccountData": ["(?<!financial )account(.){0,20}(data|information|detail)"],
            "ProfileData": ["profile (data|information|detail)"],
            "ProfilePicture": ["profile picture", "profile photo", "avatar"],
            "Username": ["username", "user name", "login name", "\\balias\\b"],
            "ThirdPartyHandle": [
                "social media(.){0,64}handle\\b",
                "third(-| )party(.){0,64}handle\\b",
            ],
            "PermissionsData": ["\\b(?<!your )permission(s)?\\b"],
            "CameraPermissions": ["\\bcamera permission(s)?\\b"],
            "MicrophonePermissions": ["\\bmicrophone permission(s)?\\b"],
            "LocationPermissions": ["\\blocation permission(s)?\\b"],
            "ContactsPermissions": ["\\bcontacts permission(s)?\\b"],
            "StoragePermissions": ["\\bstorage permission(s)?\\b"],
            "NotificationPermissions": ["\\bnotification permission(s)?\\b"],
            "Lighting": ["\\blighting\\b"],
            "SensorData": ["sensor(.){0,20}(data|information|reading)"],
            "EnvironmentalData": [
                "(environmental|environment) (data|information|detail)",
                "surrounding environment",
                "environmental characteristics value",
                "\\becv\\b",
            ],
            "MotionData": [
                "\\bmotion\\b",
                "(?<!free )\\bmovement(?:s)?\\b(?! (?:around|on) the (website|app|site))",
            ],
            "PresenceData": ["presence"],
            "AmbientLightData": ["ambient light"],
            "TemperatureData": ["temperature"],
            "HumidityData": ["humidity"],
            "MoistureData": ["moisture"],
            "NoiseLevel": ["noise level", "sound level", "noise decibel"],
            "PrecipitationData": ["precipitation", "\\brain\\b"],
            "WindData": ["\\bwind\\b"],
            "AirQualityData": ["air quality"],
            "CarbonMonoxideData": ["carbon monoxide", "\\bCO(?!-)\\b"],
            "CarbonDioxideData": ["carbon dioxide", "CO2"],
            "SmokeData": ["smoke"],
            "OutdoorData": ["outdoor (data|information|detail)"],
            "WeatherData": ["weather(.){0,20}(data|information|detail)"],
            "WaterConsumptionData": ["water consumption", "water usage"],
            "GasConsumptionData": ["gas consumption", "gas usage"],
            "DirtLevel": ["dirt level", "dust level", "level(s)? of dirt"],
            "PresenceOfPeople": [
                "presence of(.){0,20}people",
                "people detected",
                "(humand|people|person)(s)? (detected|present|detection|presence)",
                "where (human|people|person)(s)? are (located|present)",
            ],
            "PresenceOfPets": ["presence of(.){0,20}pet", "pets detected"],
            "CleaningHistory": ["cleaning history"],
            "HeatingSchedule": ["heating schedule", "heating timetable"],
            "AppName": ["app(.){0,16}name", "name of app"],
            "HomeName": ["home(.){0,16}name", "name of home"],
            "FloorplanData": ["floorplan"],
            "FloorType": ["floor type", "type(s)? of floor"],
            "ObjectData": [
                "object (data|information|detail)",
                "type(s)? of object",
                "obstacle",
            ],
            "RoomName": ["room name", "name of room"],
            "OperatingPowerData": ["operating power"],
            "EnergyConsumptionData": [
                "(energy|power) consumption",
                "(energy|power) usage",
            ],
            "VoltageData": ["voltage"],
            "EnergyProductivityData": ["energy productivity", "energy production data"],
            "HealthData": [
                "(?<!device )(?<!product )(health|fitness)(.){0,20}(data|information)"
            ],
            "HealthStatus": ["health(.){0,20}status"],
            "SleepData": [
                "sleep(.){0,20}(data|information)",
                "nap (data|information|pattern)",
            ],
            "CoughingData": ["coughing"],
            "SnoringData": ["snoring"],
            "HeartRateData": ["heart rate", "heart-rate"],
            "StepCountData": ["step count", "step-count", "steps taken"],
            "FitnessGoals": ["fitness goal", "exercise goal", "activity goal"],
            "HeartRate": ["heart rate", "heart-rate"],
            "BloodPressure": ["blood pressure"],
            "BloodSugar": ["blood sugar", "glucose level"],
            "BloodOxygenLevel": ["blood oxygen level", "SpO2"],
            "BMI": ["\\bBMI\\bb", "body mass index"],
            "BodyFat": ["body fat"],
            "MuscleMass": ["muscle mass"],
            "MetabolicInformation": ["metabolic (information|data)"],
            "MenstrualCycleData": ["menstrual cycle", "period (data|information)"],
            "BoneDensity": ["bone density"],
            "DesignFiles": ["design file", "design document", "design specification"],
            "FinancialData": ["financial(.){0,20}(data|information|detail)"],
            "IncomeData": ["income(.){0,20}(data|information|detail)", "salary"],
            "FinancialStatus": ["(financial|economic)(.){0,20}status"],
            "CreditScore": ["credit(.){0,20}status", "credit score", "credit history"],
            "MembershipData": [
                "membership (data|information|details|level)",
                "membership status",
            ],
            "AudioData": [
                "(audio|sound|noise)(.){0,32}(data|signal|recording|information|content|file)",
                "(recognition|detect)(.){0,48}(audio|sound|voice)",
            ],
            "VideoData": [
                "(video|visual)(.){0,20}(data|signal|recording|content|file|information)",
                "videos",
                "(video|film) footage",
                "\\ba video\\b",
            ],
            "ImageData": [
                "(image|photo)(.){0,20}data",
                "image(s)?\\b",
                "photo(s)?\\b",
                "picture(s)?\\b",
                "photograph(s)?\\b",
                "graphic(s)?\\b",
            ],
            "Screenshots": ["screenshot", "screen capture"],
            "TouchData": ["\\btouch(.){0,20}(data|information|interaction|signal)"],
            "VoiceCommands": ["voice command", "voice prompt"],
            "VoiceCharacteristics": ["voice characteristic", "voice feature"],
            "TextData": ["\\btext(.){0,20}(data|information|content)"],
            "Drawings": [
                "\\bdrawing(s)?\\b",
                "\\bsketch(es)?\\b",
                "\\billustration(s)?\\b",
            ],
            "Music": ["\\bmusic\\b", "musical (data|information|content|file)"],
            "OtherFileData": ["other file(s)?", "other document(s)?", "other content"],
            "TemporaryFiles": ["\\btemporary file(s)?\\b"],
            "PersonalBehaviorData": [
                "personal behavior",
                "behavioral (data|information)",
            ],
            "HabitData": ["\\bhabit(s)?\\b"],
            "InterestData": [
                "(?<!might )(?<!of )(?<!legitimate )(?<!public )\\binterest(s)?\\b"
            ],
            "HobbyData": ["\\bhobby\\b", "\\bhobbies\\b"],
            "PurchaseMotivation": ["purchase motivation", "motivation for purchase"],
            "BiometricData": [
                "biometric (data|information)",
                "biometric (processing|assessment)",
            ],
            "FacialData": [
                "facial (data|information|feature)",
                "scan of(.){0,20}face",
                "(recognition|detect)(.){0,48}face",
                "facial recognition (data|information)",
                "facial (scan|image)",
                "face prints",
            ],
            "VoiceData": [
                "voice(.){0,20}(data|information|interaction)",
                "voice (recordings|quer(y|ies)|input)",
                "(recognition|detect)(.){0,48}voice",
            ],
            "FingerprintData": ["fingerprint (data|information)"],
            "Submissions": ["\\bsubmission(s)?\\b"],
            "Feedback": ["\\bfeedback\\b(?! service)"],
            "Comments": ["\\bcomment(s)?\\b"],
            "Opinions": ["\\bopinion(s)?\\b"],
            "Reviews": ["(?<!regularly )\\breview(s)?\\b"],
            "ServicesData": ["service(s)? (data|information)"],
            "ServiceType": ["service type", "type of service"],
            "CallRecords": [
                "call(ing)? record",
                "phone calls",
                "recording(s)? of(.){0,20}(calls)",
            ],
            "ChatHistory": [
                "chat history",
                "chat messages",
                "\\bencrypted messages\\b",
                "chat transcripts",
            ],
            "CommunicationRecords": [
                "communication record",
                "communication history",
                "records(.){0,20}correspondence",
            ],
            "RegistrationData": ["registration (data|information|detail)"],
            "SecurityInformation": [
                "security(-related)?(.){0,12}(information|data|detail)",
                "security status",
            ],
            "TamperStatus": ["tamper status", "tampering (data|information)"],
            "CredentialData": [
                "\\bcredential(s)?\\b",
                "(login|access|authentication) (data|information)",
            ],
            "SecurityPin": ["security pin", "PIN code"],
            "Password": ["password", "passcode"],
            "AuthToken": ["\\bauth token\\b", "\\bauthentication token\\b"],
            "WrittenPermissions": ["\\bwritten permission\\b", "\\bwritten consent\\b"],
            "OrderData": [
                "order (data|information)",
                "purchas(e|ing)? (data|information)",
                "information about(.){0,20}purchase",
            ],
            "OrderHistory": [
                "order history",
                "order activity",
                "purchase(.){0,20}history",
                "products purchased",
                "records of (orders|purchases)",
            ],
            "OrderNumber": ["order number", "order(s)? id"],
            "InvoiceData": [
                "invoice (data|information|detail)",
                "invoicing (data|information|detail)",
            ],
            "PurchaseDate": ["purchase date", "order(s)? date", "order(s)? timestamp"],
            "PaymentData": ["payment(.){0,20}(data|information|detail)"],
            "PaymentAmount": [
                "(payment|purchase) (amount|price)",
                "amount paid",
                "(total|purchase) amount",
            ],
            "PaymentMethod": ["payment method", "(method|form) of payment"],
            "BillingData": ["billing(.){0,20}(data|information|detail)"],
            "BillingReceipts": [
                "billing receipt",
                "payment receipt",
                "purchase receipt",
            ],
            "TransactionData": [
                "(?!in such )transaction(.){0,20}(data|information|detail)"
            ],
            "InAppTransactions": ["in(-| )app transaction", "in(-| )app purchase"],
            "ShippingInformation": ["(shipping|delivery)(.){0,20}(information|data)"],
            "CommercialInformation": ["commercial(.){0,20}(information|data|detail)"],
            "CreditCardInformation": [
                "credit(.){0,20}card(.){0,20}(information|data|detail)"
            ],
            "CreditCardNumber": ["credit(.){0,20}card(.){0,20}number"],
            "DebitCardInformation": [
                "debit(.){0,20}card(.){0,20}(information|data|detail)"
            ],
            "BankAccountInformation": [
                "bank account(.){0,20}(information|data|detail)",
                "financial account(.){0,20}(information|data|detail)",
            ],
            "BankAccountNumber": ["bank account number"],
            "BankHolderName": ["bank account holder name", "name on bank account"],
            "PaymentCardInformation": [
                "payment(.){0,20}card(.){0,20}(information|data|detail)"
            ],
            "PaymentCardNumber": ["payment card number"],
            "CardExpiryDate": [
                "\\bcard expiry date\\b",
                "\\bcard expiration date\\b",
                "\\bcredit card expiry\\b",
            ],
            "CustomerList": ["customer list"],
            "CustomerRecords": [
                "customer (record|data|information|detail)",
                "information about(.){0,20}customer",
            ],
            "ApplicationData": ["job application (data|information)", "\\bCV\\b"],
            "Qualifications": ["qualification(s)?"],
            "CallStatus": ["call status"],
            "AmbientSound": ["ambient sound", "background sound"],
            "UserGeneratedContent": [
                "user(-| )generated content",
                "\\bUGC\\b",
                "\\buser content\\b",
            ],
            "Likes": ["\\blikes\\b"],
            "Follows": ["(?<!as )\\bfollow(s)?\\b"],
            "Contacts": ["\\bcontacts\\b"],
            "ContentUseHistory": ["content use history", "content viewing history"],
            "VirusDefinitions": [
                "virus definition(s)?",
                "malware definition(s)?",
                "virus definition list",
            ],
            "ContestData": ["contest (data|information|entry|detail)"],
            "BusinessInformation": ["\\bbusiness (information|data|detail)\\b"],
            "NumberOfEmployees": ["\\bnumber of employees\\b", "\\bemployee count\\b"],
            "BusinessModel": ["\\bbusiness model\\b"],
        }
    ),
    track_conv=AttributePattern.from_dict(
        {
            "Cookies": ["\\bcookie(s)?\\b"],
            "WebBeacons": ["\\bbeacon(s)?\\b", "web(-)?beacon(s)?"],
            "TrackingPixel": [
                "\\btracking pixel(s)?\\b",
                "\\bpixel tag(s)?\\b",
                "(?=.*pixel)(?=.*(html|email|cookie|tracking))",
            ],
            "ClearGIF": ["\\bclear gif(s)?\\b", "\\bone-pixel gifs\\b"],
            "SDK": ["\\bsdk(s)?\\b"],
            "SimilarTechnologies": [
                "\\bsimilar ((tracking|identifier) )?technolog(y|ies)?\\b",
                "\\bother web tools\\b",
                "\\bsimilar tracking\\b",
                "tracking mechanism(s)?\\b",
            ],
        }
    ),
    method_source=AttributePattern.from_dict(
        {
            "UserProvided": [
                "\\byou(.){0,20}(provide|submit|enter|upload|give|share|send)",
                "\\b(enter|submit|provide)(.){0,20}by you",
                "\\bto (enter|submit|provide)\\b",
            ],
            "AutomaticallyCollected": [
                "automatically(.){0,20}(collect|gather|track|record)",
                "\\bautomatic",
                "\\by your (device|browser|computer|mobile|system)\\b",
            ],
            "ThirdPartyProvided": [
                "(?=.*(obtain|receive|collect from))(?=.*(third(-| )party|external source))",
                "\\breceive.*from.*(partner|vendor|affiliate|provider)\\b",
            ],
            "DataCombination": [
                "\\bderive(d)?\\b",
                "\\binferre(d)?\\b",
                "\\bcombine(d)?\\b",
            ],
            "AIAnalysis": [
                "(?=.*\\b(use|using|through)\\b)(?=.*\\b(artificial intelligence|AI|machine learning|ML)\\b)"
            ],
            "SocialMedia": [
                "\\bsocial media\\b",
                "\\bsocial network(ing)?\\b",
                "\\bsocial plug-?in(s)?\\b",
            ],
            "IndirectCollection": ["(?=.*\\bindirectly)(?=.*(collect|obtain|gather))"],
            "Public": [
                "\\bpublicly\\b",
                "from public sources",
                "\\bdata you make public",
                "\\bmade public by you\\b",
            ],
            "Interaction": [
                "\\binteraction(s)?\\b",
                "\\bcommunicat(e|ion)(s)?\\b",
                "(?=.*when)(?=.*interact)",
                "(course of)(.){0,32}(relationship)",
                "\\bduring.*\\b(use|visit)\\b",
            ],
            "VoluntaryProvided": [
                "\\bvoluntarily\\b",
                "\\bvoluntary\\b",
                "\\bif you (choose|elect|opt) to\\b",
                "\\boptional\\b",
                "(?=.*\\b(right to choose|not obliged))(?=.*(provide|share|submit|give|upload))",
            ],
            "Buying": [
                "(?=.*\\bwe\\b)(?=.*\\b(purchase|buy|acquire)\\b)(?=.*\\b(data|information)\\b)"
            ],
        }
    ),
    descriptive=AttributePattern.from_dict(
        {
            "ServiceProvider": [
                "service (provider|partner|process(er|or))",
                "\\bthird(-| )party provider(s)?\\b",
            ],
            "PaymentServiceProvider": [
                "(payment|check-out)(.){0,64}(provider|partner|process(er|or)|service|institution)",
                "payment gateway",
            ],
            "CreditInstitution": [
                "credit(.){0,64}(institution|union|bank|provider|agenc(y|ies))",
                "\\bfinancial institution",
            ],
            "InternetServiceProvider": [
                "internet (service provider|provider|partner)",
                "\\bisp\\b",
            ],
            "TransportCompany": [
                "(shipping|delivery|logistic|freight)(.){0,64}(company|service|provider|partner)",
                "\\bcourier",
            ],
            "HostingProvider": ["(hosting)(.){0,64}(provider|partner|service)"],
            "StorageServiceProvider": [
                "(storage)(.){0,64}(provider|partner|service)",
                "data centers",
                "database management provider",
            ],
            "SocialMediaProvider": [
                "(social media)(.){0,64}(provider|partner|service|platform|site|feature)",
                "\\bsocial network",
                "\\bsocial plugin(s)?\\b",
            ],
            "Vendor": ["\\bvendor\\b", "\\breseller\\b", "\\bdistributor\\b"],
            "Supplier": ["\\bsupplier(s)?\\b"],
            "SubContractors": [
                "\\bsub[- ]?contractor(s)?\\b",
                "independent contractor",
                "\\bcontractors\\b",
            ],
            "Adviser": [
                "\\badviser(s)?\\b",
                "\\badvisor(s)?\\b",
                "\\bconsultant(s)?\\b",
            ],
            "Buyer/Investor": [
                "\\b(potential|prospective) (buyer|investor|acquirer)(s)?\\b",
                "(purchaser|acquirer) of(.){0,20} business",
                "investor(s)? in(.){0,20}business",
                "third(-| )party acquirer",
                "\\bnew holder\\b",
            ],
            "RatingPlatform": [
                "\\brating platform(s)?\\b",
                "\\breview platform(s)?\\b",
            ],
            "MarketingAffiliate": [
                "\\bmarketing affiliate(s)?\\b",
                "\\bmarketing partner(s)?\\b",
                "affiliate marketing (company|companies|entity|entities|partner|provider)",
            ],
            "AdvertisingAgency": [
                "\\badvertising agency(ies)?\\b",
                "\\bad agency(ies)?\\b",
                "marketing (agency|partner|service|platform)",
            ],
            "AdvertisingNetwork": [
                "\\badvertising network(s)?\\b",
                "\\bad network(s)?\\b",
            ],
            "SoftwareDeveloper": ["\\bsoftware developer(s)?\\b", "app developer(s)?"],
            "CustomerServiceProvider": [
                "\\bcustomer (service|support) (provider|partner|service)\\b"
            ],
            "BusinessPartner": ["\\bbusiness partner(s)?\\b"],
            "CloudService": ["\\bcloud (computing )?(provider|partner|service)"],
            "AnalyticsService": [
                "\\banalytic(s)? (service|provider|partner|compan(y|ies)|platform)"
            ],
            "CompatibleApp": [
                "third(-| )party(.){0,20}app",
                "\\bapp made by (third(-| )party|external)",
                "(compatible|external) app",
            ],
            "CompatibleDevice": [
                "third(-| )party(.){0,20}(device|product)",
                "\\bdevice made by (third(-| )party|external)",
                "(compatible|external) device",
            ],
            "CompatibleService": [
                "third(-| )party(.){0,20}service",
                "\\bservice made by (third(-| )party|external)",
                "(compatible|external) service",
            ],
            "PartnerIntegrations": [
                "\\bpartner integration(s)?\\b",
                "connectivity platform",
                "\\bintegrated service(s)?\\b",
            ],
            "ExternalAccount": [
                "\\bexternal account(s)?\\b",
                "account from (third(-| )party|external)",
                "partner user account",
            ],
            "ThirdPartySite": [
                "\\bthird(-| )party (website|site|page)",
                "(external|linked) (website|site|page)",
            ],
            "ThirdPartyStore": [
                "third(-| )party(.){0,20}(store|marketplace)",
                "external (app|software|online) store",
            ],
            "SecurityAuthorities": ["\\bsecurity authority(ies)?\\b"],
            "Court": ["\\bcourt(s)?\\b", "\\bjudicial (body|bodies)\\b"],
            "LawEnforcement": [
                "\\blaw enforcement (agency|agencies|authority|authorities|body)\\b",
                "legal(.){0,20}authorit(y|ies)",
                "\\bpolice\\b",
            ],
            "RegulatoryAgencies": [
                "\\bregulatory (agency|agencies|authority|authorities|body)\\b"
            ],
            "GovernmentAgencies": [
                "\\bgovernment (agency|agencies|authority|authorities|body)\\b",
                "public authorit(y|ies)",
            ],
            "DataPartner": ["\\bdata partner(s)?\\b"],
            "FraudPreventionService": [
                "fraud (prevention|detection) (service|provider|partner)"
            ],
            "SmartAssistant": ["\\bsmart assistant(s)?\\b"],
            "VoiceAssistent": ["\\bvoice assistent(s)?\\b"],
            "AiServices": [
                "(service|provider|partner|compan(y|ies))(.){0,64}(artificial intelligence|AI|machine learning|ML)",
                "\\bAI service(s)?\\b",
                "\\bartificial intelligence service(s)?\\b",
            ],
            "ContentProvider": [
                "\\bcontent provider(s)?\\b",
                "(provider|contributor)(s)? of content",
            ],
            "Affiliates": [
                "\\baffiliate(s)?\\b",
                "affiliated (company|companies|entity|entities)",
            ],
            "ParentCompany": ["\\bparent compan(y|ies)"],
            "Subsidiaries": ["\\bsubsidiar(y|ies)\\b"],
            "ContentDeliveryNetwork": [
                "\\bcdn\\b",
                "\\bcontent delivery network(s)?\\b",
            ],
            "NetworkOperator": [
                "\\bnetwork operator(s)?\\b",
                "\\btelecommunication(s)? (provider|operator)(s)?\\b",
            ],
            "EcosystemCompanies": [
                "companies forming(.){0,20}ecosystem",
                "ecosystem (companies|entities|partners)",
            ],
            "Partners": ["\\bthird(-| )party partner"],
            "Accountant": [
                "\\baccountant(s)?\\b",
                "\\baccounting (firm|service|partner)",
            ],
            "Auditors": ["\\bauditor(s)?\\b"],
            "Lawyers": [
                "\\blawyer(s)?\\b",
                "\\battorney(s)?\\b",
                "\\blegal counsel\\b",
                "\\blaw firm(s)?\\b",
            ],
            "DataController": [
                "\\bdata controller(s)?\\b",
                "\\bjoint controller(s)?\\b",
            ],
            "AttributionCompanies": [
                "\\battribution (company|companies|entity|entities)\\b"
            ],
            "ThirdPartyEmployee": [
                "\\bthird(-| )party employee(s)?\\b",
                "employee(s)? of (third(-| )party|external)",
            ],
            "BackupService": ["\\bbackup (service|provider|partner)\\b"],
            "CustomerRelationshipManagement": [
                "\\bcrm\\b",
                "customer relationship manag(e|ement)",
            ],
            "ECommercePlatform": ["\\be-commerce platform(s)?\\b"],
            "EmailServiceProvider": ["\\bemail (service|provider|partner)\\b"],
            "SecurityServiceProvider": ["security (service provider|provider|partner)"],
            "IdentityVerificationService": [
                "identity verification (service|provider|partner)"
            ],
            "Insurer": [
                "\\binsurer(s)?\\b",
                "\\binsurance (company|companies|provider)(s)?\\b",
            ],
        }
    ),
    country=AttributePattern.from_dict(
        {
            "North America": ["\\bnorth america\\b"],
            "South America": ["\\bsouth america\\b"],
            "Central America": ["\\bcentral america\\b"],
            "Europe": ["\\beurope\\b"],
            "European Union": ["\\beuropean union\\b", "\\beu\\b"],
            "EEA": ["\\beea\\b", "\\beuropean economic area\\b"],
            "Asia": ["\\basia\\b"],
            "Africa": ["\\bafrica\\b"],
            "Oceania": ["\\boceania\\b"],
            "Middle East": ["\\bmiddle east\\b"],
            "International": [
                "\\binternational\\b",
                "\\bworldwide\\b",
                "\\bglobally\\b",
                "\\baround the world\\b",
                "global(.){0,20}(infrastructure|service|operation|presence|reach|coverage|facilit(y|ies))",
                "\\boverseas\\b",
            ],
            "Residence State": [
                "\\b(residence|home) (state|country)\\b",
                "\\b(state|country) of residence\\b",
                "\\b(state|country) where you live\\b",
                "\\byour (state|country|jurisdiction)\\b",
            ],
            "CountriesOutsideOf": [
                "\\boutside (of|the)\\b",
                "\\bnot in\\b",
                "\\bout (of|the)\\b",
            ],
            "AndOther": ["\\bother countr(y|ies)\\b"],
            "California": ["\\bcalifornia\\b"],
            "United States": [
                "\\bunited states\\b",
                "\\busa\\b",
                "\\bu\\.s\\.a\\.\\b",
                "\\bu\\.s\\.\\b",
                "\\bamerica\\b",
            ],
            "United Kingdom": [
                "\\bunited kingdom\\b",
                "\\buk\\b",
                "\\bu\\.k\\.\\b",
                "\\bgreat britain\\b",
                "\\bbritain\\b",
            ],
            "Canada": ["\\bcanada\\b"],
            "Australia": ["\\baustralia\\b"],
            "New Zealand": ["\\bnew zealand\\b"],
            "Germany": ["\\bgermany\\b"],
            "France": ["\\bfrance\\b"],
            "Italy": ["\\bitaly\\b"],
            "Spain": ["\\bspain\\b"],
            "Portugal": ["\\bportugal\\b"],
            "Netherlands": ["\\bnetherlands\\b", "\\bholland\\b"],
            "Belgium": ["\\bbelgium\\b"],
            "Switzerland": ["\\bswitzerland\\b"],
            "Austria": ["\\baustria\\b"],
            "Sweden": ["\\bsweden\\b"],
            "Norway": ["\\bnorway\\b"],
            "Denmark": ["\\bdenmark\\b"],
            "Finland": ["\\bfinland\\b"],
            "Iceland": ["\\biceland\\b"],
            "Ireland": ["\\bireland\\b"],
            "Poland": ["\\bpoland\\b"],
            "Czech Republic": ["\\bczech republic\\b", "\\bczechia\\b"],
            "Slovakia": ["\\bslovakia\\b"],
            "Hungary": ["\\bhungary\\b"],
            "Romania": ["\\bromania\\b"],
            "Bulgaria": ["\\bbulgaria\\b"],
            "Greece": ["\\bgreece\\b"],
            "Croatia": ["\\bcroatia\\b"],
            "Slovenia": ["\\bslovenia\\b"],
            "Estonia": ["\\bestonia\\b"],
            "Latvia": ["\\blatvia\\b"],
            "Lithuania": ["\\blithuania\\b"],
            "Luxembourg": ["\\bluxembourg\\b"],
            "Malta": ["\\bmalta\\b"],
            "Cyprus": ["\\bcyprus\\b"],
            "Russia": ["\\brussia\\b", "\\brussian federation\\b"],
            "Ukraine": ["\\bukraine\\b"],
            "Belarus": ["\\bbelarus\\b"],
            "Moldova": ["\\bmoldova\\b"],
            "Serbia": ["\\bserbia\\b"],
            "Bosnia and Herzegovina": ["\\bbosnia\\b", "\\bbosnia and herzegovina\\b"],
            "Albania": ["\\balbania\\b"],
            "North Macedonia": ["\\bnorth macedonia\\b", "\\bmacedonia\\b"],
            "Montenegro": ["\\bmontenegro\\b"],
            "Kosovo": ["\\bkosovo\\b"],
            "Turkey": ["\\bturkey\\b"],
            "China": [
                "\\bchina\\b",
                "\\bprc\\b",
                "\\bpeople's republic of china\\b",
                "\\bchinese mainland\\b",
            ],
            "Japan": ["\\bjapan\\b"],
            "South Korea": ["\\bsouth korea\\b", "\\brepublic of korea\\b"],
            "North Korea": ["\\bnorth korea\\b", "\\bdprk\\b"],
            "Taiwan": ["\\btaiwan\\b"],
            "Hong Kong": ["\\bhong kong\\b"],
            "Macau": ["\\bmacau\\b", "\\bmacao\\b"],
            "Singapore": ["\\bsingapore\\b"],
            "Malaysia": ["\\bmalaysia\\b"],
            "Indonesia": ["\\bindonesia\\b"],
            "Thailand": ["\\bthailand\\b"],
            "Vietnam": ["\\bvietnam\\b"],
            "Philippines": ["\\bphilippines\\b"],
            "Myanmar": ["\\bmyanmar\\b", "\\bburma\\b"],
            "Cambodia": ["\\bcambodia\\b"],
            "Laos": ["\\blaos\\b"],
            "Brunei": ["\\bbrunei\\b"],
            "India": ["\\bindia\\b"],
            "Pakistan": ["\\bpakistan\\b"],
            "Bangladesh": ["\\bbangladesh\\b"],
            "Sri Lanka": ["\\bsri lanka\\b"],
            "Nepal": ["\\bnepal\\b"],
            "Bhutan": ["\\bbhutan\\b"],
            "Maldives": ["\\bmaldives\\b"],
            "Afghanistan": ["\\bafghanistan\\b"],
            "Iran": ["\\biran\\b"],
            "Iraq": ["\\biraq\\b"],
            "Saudi Arabia": ["\\bsaudi arabia\\b"],
            "United Arab Emirates": [
                "\\bunited arab emirates\\b",
                "\\buae\\b",
                "\\bu\\.a\\.e\\.\\b",
            ],
            "Qatar": ["\\bqatar\\b"],
            "Kuwait": ["\\bkuwait\\b"],
            "Bahrain": ["\\bbahrain\\b"],
            "Oman": ["\\boman\\b"],
            "Yemen": ["\\byemen\\b"],
            "Jordan": ["\\bjordan\\b"],
            "Lebanon": ["\\blebanon\\b"],
            "Syria": ["\\bsyria\\b"],
            "Israel": ["\\bisrael\\b"],
            "Palestine": ["\\bpalestine\\b"],
            "Egypt": ["\\begypt\\b"],
            "Libya": ["\\blibya\\b"],
            "Tunisia": ["\\btunisia\\b"],
            "Algeria": ["\\balgeria\\b"],
            "Morocco": ["\\bmorocco\\b"],
            "Sudan": ["\\bsudan\\b"],
            "South Sudan": ["\\bsouth sudan\\b"],
            "Ethiopia": ["\\bethiopia\\b"],
            "Kenya": ["\\bkenya\\b"],
            "Tanzania": ["\\btanzania\\b"],
            "Uganda": ["\\buganda\\b"],
            "Rwanda": ["\\brwanda\\b"],
            "Burundi": ["\\bburundi\\b"],
            "Somalia": ["\\bsomalia\\b"],
            "Djibouti": ["\\bdjibouti\\b"],
            "Eritrea": ["\\beritrea\\b"],
            "Nigeria": ["\\bnigeria\\b"],
            "Ghana": ["\\bghana\\b"],
            "Ivory Coast": ["\\bivory coast\\b", "\\bcote d'ivoire\\b"],
            "Senegal": ["\\bsenegal\\b"],
            "Mali": ["\\bmali\\b"],
            "Burkina Faso": ["\\bburkina faso\\b"],
            "Niger": ["\\bniger\\b"],
            "Chad": ["\\bchad\\b"],
            "Cameroon": ["\\bcameroon\\b"],
            "Central African Republic": ["\\bcentral african republic\\b"],
            "Gabon": ["\\bgabon\\b"],
            "Congo": ["\\bcongo\\b", "\\brepublic of the congo\\b"],
            "Democratic Republic of Congo": [
                "\\bdemocratic republic of congo\\b",
                "\\bdrc\\b",
                "\\bd\\.r\\.c\\.\\b",
            ],
            "Angola": ["\\bangola\\b"],
            "Zambia": ["\\bzambia\\b"],
            "Zimbabwe": ["\\bzimbabwe\\b"],
            "Mozambique": ["\\bmozambique\\b"],
            "Malawi": ["\\bmalawi\\b"],
            "Botswana": ["\\bbotswana\\b"],
            "Namibia": ["\\bnamibia\\b"],
            "South Africa": ["\\bsouth africa\\b"],
            "Lesotho": ["\\blesotho\\b"],
            "Eswatini": ["\\beswatini\\b", "\\bswaziland\\b"],
            "Madagascar": ["\\bmadagascar\\b"],
            "Mauritius": ["\\bmauritius\\b"],
            "Seychelles": ["\\bseychelles\\b"],
            "Comoros": ["\\bcomoros\\b"],
            "Cape Verde": ["\\bcape verde\\b"],
            "Sao Tome and Principe": ["\\bsao tome\\b"],
            "Equatorial Guinea": ["\\bequatorial guinea\\b"],
            "Guinea": ["\\bguinea\\b"],
            "Guinea-Bissau": ["\\bguinea-bissau\\b"],
            "Sierra Leone": ["\\bsierra leone\\b"],
            "Liberia": ["\\bliberia\\b"],
            "Togo": ["\\btogo\\b"],
            "Benin": ["\\bbenin\\b"],
            "Mauritania": ["\\bmauritania\\b"],
            "Gambia": ["\\bgambia\\b"],
            "Mexico": ["\\bmexico\\b"],
            "Guatemala": ["\\bguatemala\\b"],
            "Belize": ["\\bbelize\\b"],
            "Honduras": ["\\bhonduras\\b"],
            "El Salvador": ["\\bel salvador\\b"],
            "Nicaragua": ["\\bnicaragua\\b"],
            "Costa Rica": ["\\bcosta rica\\b"],
            "Panama": ["\\bpanama\\b"],
            "Cuba": ["\\bcuba\\b"],
            "Jamaica": ["\\bjamaica\\b"],
            "Haiti": ["\\bhaiti\\b"],
            "Dominican Republic": ["\\bdominican republic\\b"],
            "Bahamas": ["\\bbahamas\\b"],
            "Trinidad and Tobago": ["\\btrinidad and tobago\\b", "\\btrinidad\\b"],
            "Barbados": ["\\bbarbados\\b"],
            "Saint Lucia": ["\\bsaint lucia\\b", "\\bst\\.? lucia\\b"],
            "Grenada": ["\\bgrenada\\b"],
            "Saint Vincent": ["\\bsaint vincent\\b", "\\bst\\.? vincent\\b"],
            "Antigua and Barbuda": ["\\bantigua\\b", "\\bantigua and barbuda\\b"],
            "Dominica": ["\\bdominica\\b"],
            "Saint Kitts": ["\\bsaint kitts\\b", "\\bst\\.? kitts\\b"],
            "Brazil": ["\\bbrazil\\b"],
            "Argentina": ["\\bargentina\\b"],
            "Chile": ["\\bchile\\b"],
            "Colombia": ["\\bcolombia\\b"],
            "Peru": ["\\bperu\\b"],
            "Venezuela": ["\\bvenezuela\\b"],
            "Ecuador": ["\\becuador\\b"],
            "Bolivia": ["\\bbolivia\\b"],
            "Paraguay": ["\\bparaguay\\b"],
            "Uruguay": ["\\buruguay\\b"],
            "Guyana": ["\\bguyana\\b"],
            "Suriname": ["\\bsuriname\\b"],
            "French Guiana": ["\\bfrench guiana\\b"],
            "Fiji": ["\\bfiji\\b"],
            "Papua New Guinea": ["\\bpapua new guinea\\b", "\\bpng\\b"],
            "Solomon Islands": ["\\bsolomon islands\\b"],
            "Vanuatu": ["\\bvanuatu\\b"],
            "Samoa": ["\\bsamoa\\b"],
            "Tonga": ["\\btonga\\b"],
            "Kiribati": ["\\bkiribati\\b"],
            "Micronesia": ["\\bmicronesia\\b"],
            "Marshall Islands": ["\\bmarshall islands\\b"],
            "Palau": ["\\bpalau\\b"],
            "Nauru": ["\\bnauru\\b"],
            "Tuvalu": ["\\btuvalu\\b"],
            "Cook Islands": ["\\bcook islands\\b"],
            "Niue": ["\\bniue\\b"],
            "Kazakhstan": ["\\bkazakhstan\\b"],
            "Uzbekistan": ["\\buzbekistan\\b"],
            "Turkmenistan": ["\\bturkmenistan\\b"],
            "Kyrgyzstan": ["\\bkyrgyzstan\\b"],
            "Tajikistan": ["\\btajikistan\\b"],
            "Mongolia": ["\\bmongolia\\b"],
            "Armenia": ["\\barmenia\\b"],
            "Azerbaijan": ["\\bazerbaijan\\b"],
            "Georgia": ["\\bgeorgia\\b"],
        }
    ),
    company=AttributePattern.from_dict(
        {
            "Amazon": ["\\bamazon(s)?\\b", "\\baws\\b"],
            "Microsoft": [
                "\\bmicrosoft\\b",
                "\\bazure\\b",
                "\\bbing\\b",
                "\\boffice 365\\b",
                "\\bskype\\b",
                "\\bonedrive\\b",
            ],
            "Apple": ["\\bapple(s)?\\b", "\\bicloud\\b", "\\bios\\b", "\\bmac(os)?\\b"],
            "Google": [
                "\\bgoogle(s)?\\b",
                "\\bgcp\\b",
                "\\bandroid\\b",
                "\\bgmail\\b",
                "\\byoutube\\b",
                "\\bchromecast\\b",
                "\\bgoogle analytics\\b",
                "\\bgoogle ads\\b",
                "\\bgoogle tag manager\\b",
                "\\bgoogle maps\\b",
                "\\bgoogle cloud\\b",
                "\\bdoubleclick\\b",
                "\\badmob\\b",
            ],
            "Facebook": [
                "\\bfacebook(s)?\\b",
                "\\bmeta\\b",
                "\\binstagram\\b",
                "\\bwhatsapp\\b",
                "\\bmeta pixel\\b",
                "\\bfacebook pixel\\b",
            ],
            "SmartThings": ["\\bsmartthing(s)?\\b"],
            "Avast": ["\\bavast\\b"],
            "Antiy": ["\\bantiy\\b"],
            "Tencent": ["\\btencent\\b", "\\bwechat\\b", "\\bqq\\b"],
            "Unity": ["\\bunity\\b"],
            "Vungle": ["\\bvungle\\b"],
            "IronSource": ["\\bironsource\\b"],
            "AppLovin": ["\\bapplovin\\b"],
            "Chartboost": ["\\bchartboost\\b"],
            "Mopub": ["\\bmopub\\b"],
            "Mytarget": ["\\bmytarget\\b"],
            "Yandex": ["\\byandex\\b"],
            "Tapjoy": ["\\btapjoy\\b"],
            "AdColony": ["\\badcolony\\b"],
            "IndusAppstore": ["\\bindusappstore\\b"],
            "Adjust": ["\\badjust\\b"],
            "Appsflyer": ["\\bappsflyer\\b"],
            "Affise": ["\\baffise\\b"],
            "Miaozhen": ["\\bmiaozhen\\b"],
            "Nielsen": ["\\bnielsen\\b"],
            "PayPal": ["\\bpaypal\\b", "\\braintree\\b"],
            "Twitter": ["\\btwitter\\b", "\\bx\\.com\\b"],
            "Instagram": ["\\binstagram\\b"],
            "Pinterest": ["\\bpinterest\\b"],
            "YouTube": ["\\byoutube\\b"],
            "LinkedIn": ["\\blinkedin\\b"],
            "Xing": ["\\bxing\\b"],
            "Kununu": ["\\bkununu\\b"],
            "RISKIFIED": ["\\briskified\\b"],
            "Stripe": ["\\bstripe\\b"],
            "Firebase": ["\\bfirebase\\b"],
            "Mailchimp": ["\\bmailchimp\\b", "\\bmandrill\\b"],
            "Spotify": ["\\bspotify\\b"],
            "Pandora": ["\\bpandora\\b"],
            "Salesforce": ["\\bsalesforce\\b", "\\btableau\\b", "\\bslack\\b"],
            "UnionPay": ["\\bunionpay\\b"],
            "WeChat": ["\\bwechat\\b", "\\bweixin\\b"],
            "Alibaba": ["\\balibaba\\b", "\\balipay\\b"],
            "Alipay": ["\\balipay\\b"],
            "Visa": ["\\bvisa\\b"],
            "MasterCard": ["\\bmastercard\\b"],
            "GarminPay": ["\\bgarmin( )?pay\\b"],
            "Venmo": ["\\bvenmo\\b"],
            "6Sense": ["\\b6sense\\b"],
            "TransUnion": ["\\btransunion\\b", "\\bsontiq\\b"],
            "PIPL": ["\\bpipl\\b"],
            "Adyen": ["\\badyen\\b"],
            "Matomo": ["\\bmatomo\\b", "\\bpiwik\\b"],
            "Shopify": ["\\bshopify\\b", "\\bshop( )?pay\\b"],
            "OpenAI": ["\\bopenai\\b", "\\bchatgpt\\b"],
            "Hotjar": ["\\bhotjar\\b"],
            "Hubspot": ["\\bhubspot\\b"],
            "Wyng": ["\\bwyng\\b"],
            "Reddit": ["\\breddit\\b"],
            "Mouseflow": ["\\bmouseflow\\b"],
            "Yahoo": ["\\byahoo\\b"],
            "Zoom": ["\\bzoom\\b"],
            "Adobe": ["\\badobe\\b", "\\badobe analytics\\b", "\\bomniture\\b"],
            "Klarna": ["\\bklarna\\b"],
            "Cloudflare": ["\\bcloudflare\\b"],
            "Akamai": ["\\bakamai\\b"],
            "Fastly": ["\\bfastly\\b"],
            "Snowflake": ["\\bsnowflake\\b"],
            "DigitalOcean": ["\\bdigitalocean\\b"],
            "TikTok": ["\\btiktok\\b", "\\bbytedance\\b"],
            "Zendesk": ["\\bzendesk\\b"],
            "Freshdesk": ["\\bfreshdesk\\b", "\\bfreshworks\\b"],
            "Datadog": ["\\bdatadog\\b"],
            "Bazaarvoice": ["\\bbazaarvoice\\b"],
            "StampedIO": ["\\bstamped\\.io\\b"],
            "RapidResponseMonitoringServices": [
                "\\brapid response monitoring services\\b"
            ],
            "Jaggaer": ["\\bjaggaer\\b"],
            "SAP": ["\\bsap\\b"],
            "Webhelp": ["\\bwebhelp\\b"],
            "GEP": ["\\bgep\\b"],
        }
    ),
    provide_service=AttributePattern.from_dict(
        {
            "OrderProcessing": [
                "\\border processing",
                "(process|handle|fulfill(ment)?|manage|make|coordinat|facilitate)(.){0,32}(order|purchase)",
                "(retailing|retail) service",
            ],
            "PaymentProcessing": [
                "\\b(payment|transaction) processing",
                "\\b(process|carry out|handle|manage|facilitate)(.){0,20}(payment|transaction)(s)?\\b",
                "\\bcheckout\\b",
                "\\bbilling\\b",
                "\\brecord (payment|transaction)(s)?\\b",
            ],
            "Shipping": [
                "\\bshipping\\b",
                "\\bdelivery(?! (speed|time))",
                "(ship|deliver|provide)(.){0,32}(order|item|goods|package)",
            ],
            "ReturnOrder": [
                "\\breturns\\b",
                "\\breturn order\\b",
                "(process|handle|manage)(.){0,32}return",
                "\\brefund(s)?\\b",
            ],
            "OrderTracking": [],
            "WarrantyService": ["\\bwarranty\\b"],
            "AfterSalesService": ["after(-| )sales (service|support|care|assistance)"],
            "PresentWebsite": [
                "\\b(provid(e|ing)|display(ing)?|present(ing)?|offer(ing)?|maintain|host|provision)(.){0,32}site",
                "site functionality",
                "ensure(.){0,32}website (availability|functionality|performance|works)",
            ],
            "ProvideApp": ["\\b(provid(e|ing)|offer(ing)?|maintain)(.){0,32}app"],
            "ProvideDevice": [
                "\\b(provid(e|ing)|offer(ing)?)(.){0,32}(device|product)"
            ],
            "PreContractualMeasures": ["\\bpre(-| )contractual measure(s)?\\b"],
            "AccountCreation": [
                "\\baccount creation\\b",
                "(create|register|maintain|set up|manage)(ing)?(.){0,32}(account|personal profile)",
                "\\bregistering\\b",
            ],
            "ProductActivation": [
                "\\bproduct activation\\b",
                "(activate|activating|activation)(.){0,32}(device|product)",
            ],
            "ServiceActivation": [
                "\\bservice activation\\b",
                "(activate|activating|activation)(.){0,32}(service|feature)",
            ],
            "DeviceRegistration": [
                "\\bdevice registration\\b",
                "\\b(register|registration|associate|bind|link)(.){0,32}(device|product)",
            ],
            "Authentication": [
                "\\bauthentication\\b",
                "\\b(log|sign)(ed)?(-| )?(in|into)\\b",
                "\\b(verify|authenticate)(.){0,32}(access|user|identity|credentials)",
                "\\bverification\\b",
                "account validation\\b",
                "\\bverification process\\b",
            ],
            "UserIdentification": [
                "\\bidentification\\b",
                "\\bidentifying\\b",
                "\\bidentify (you|your)\\b",
            ],
            "SocialLogin": [
                "\\bsocial (log(-| )?in|sign(-| )?in)\\b",
                "(log(-| )?in|sign(-| )?in)(.){0,32}(using|with)(.){0,32}(social media|social network)",
            ],
            "Monitoring": [
                "\\b(?!health )monitoring\\b",
                "\\b(monitor|analyze)(.){0,20}(usage|performance|traffic)",
            ],
            "HealthMonitoring": [
                "\\b(health|fitness)(.){0,20}monitoring\\b",
                "(monitor|track|measure)(.){0,32}(health|fitness)(.){0,32}(status|condition|metrics|data)",
            ],
            "WebHosting": ["\\bweb hosting\\b", "\\bhosting service"],
            "Recruiting": [
                "\\brecruiting\\b",
                "\\bjob application\\b",
                "\\bapply (to|for) (becoming|become)\\b",
            ],
            "CreditWorthiness": [
                "\\baccess(.){0,20}reliability",
                "\\bcredit evaluation purpos",
            ],
            "Comfort": [
                "\\bkeep(.){0,32}comfort",
                "(maintain|provide)(.){0,64}comfort",
                "\\bmore helpful\\b",
                "\\buser-friendly\\b",
                "\\b(optimize|improve|better|greater|enhance|best)(.){0,20}experience",
                "\\bhelpful experience\\b",
                "\\bmake it easier\\b",
                "\\bsatisfactory(.){0,20}(product|service|experience)\\b",
            ],
            "PersonalizeContent": [
                "\\b((personaliz|customiz)(e|ing|ation|ed))\\b",
                "\\btailor(ed|ing)?(.){0,32}(service|content|experience)",
                "\\b(which|what)(.){0,32}(relevant|interesting)",
                "previously been interested in",
                "more (relevant|interesting|engaging) to you",
                "you(.){0,20}interested in",
                "predict your (interests|preferences)",
                "(appropriate|relevant) to your (interests|preferences)",
                "based on(.){0,48}you(.){0,32}(use|installed|viewed|purchase|install|watched|accessed)",
            ],
            "Updates": [
                "(software|service|system) (update|optimization)",
                "\\bprovide(ing)?(.){0,32}(updates)",
            ],
            "Upload/Download": ["\\b(upload|download)(.){0,20}process\\b"],
            "SyncContent": [
                "\\b(synchronization|synchronize)",
                "(save|store|sync)(.){0,64}across",
                "(sync|synchroniz)(.){0,32}(content|data|information|files|settings)",
            ],
            "LocalizeContent": [
                "\\blocaliz(e|ing|ation)\\b",
                "\\bgeo(-)?targeting\\b",
                "(provide|offer|deliver)(.){0,32}(content|service)(.){0,32}(in|for)(.){0,32}(your|my)?(location|region|country|language)",
                "\\baddress regional\\b",
            ],
            "EstimateBodyMetrics": [
                "\\bestimate(.){0,48}(body|health|fitness)(.){0,48}metrics"
            ],
            "VideoAnalysis": [
                "\\bvideo analysis\\b",
                "\\banalyze(ing)?(.){0,32}video",
                "camera processing",
                "(anaylze|process)(ing)?(.){0,48}(video|footage|images)",
            ],
            "PersonDetection": [
                "\\b(person|human) detection\\b",
                "(detect|infer)(ing)?(.){0,32}(person|human|individual)",
            ],
            "ActivityDescription": [
                "\\b(activity|action) description\\b",
                "(describe|description|summary|summarize|identify|recognize)(ing)?(.){0,32}(activity|action|movement)",
            ],
            "CountVisits": ["count(ing)?(.){0,32}(visits)"],
            "RecommendSettings": [
                "(recommend|suggest)(ing)?(.){0,32}(settings|configurations)",
                "(setting|configuration) (recommendation|suggestion)",
            ],
            "ProvideUsageInsights": [
                "(provide|offer|deliver)(.){0,32}(usage|performance)(.){0,32}(insights|analytics|reports)"
            ],
            "Logging": ["\\blogging\\b", "\\bcreate(.){0,20}logs\\b"],
            "CloudBasedControl": ["cloud-based control\\b"],
            "NightVision": ["\\bnight(-| )vision\\b"],
            "MotionDetection": [
                "\\bmotion detection\\b",
                "(detect|detection|identify)(ing)?(.){0,32}motion",
                "\\b(when|if)(.){0,48}(door|window)\\b",
                "\\bmotion(.){0,20}(detected|detection|detecting)\\b",
            ],
            "ThirdPartyCompatibility": [
                "\\b(?=.*work with|connect|link)(?=.*(third(-| )party)|external|3rd(-| )party)(?=.*(device|product|service|feature|plugin))"
            ],
            "StorePreferences": [
                "(store|save|remember(.){0,32}(preference|setting|configuration)(s)?)"
            ],
            "MembershipManagement": [
                "\\bmembership management\\b",
                "(manage|handle|process|provide)(.){0,64}(membership)",
            ],
            "SpeedUp": [
                "\\b(increase|improve|optimize|faster)(.){0,32}(speed|time)\\b"
            ],
            "PromotionalActivities": [
                "(?=.*(event|promotion|competition|contest|activit(y|ies)))(?=.*(participation|attendance|registration|entry|sign(-| )up|take part|enter (into|a)|handling))",
                "(carry out|organize|run|manage|conduct)(.){0,32}(promotion|event|competition|contest|activit(y|ies))",
            ],
            "RecommendPurchases": [
                "(recommend|suggest)(ing)?(.){0,64}(product|service|item|purchase|buy)(s)?"
            ],
            "AutomaticPurchases": [
                "(automatic|auto)(.){0,32}(ship|purchase|buy)(s)?",
                "(make|process|handle|facilitate)(.){0,32}(automatic|auto)(.){0,32}(purchase|buy)(s)?",
            ],
            "SubscriptionManagement": [
                "\\bsubscription management\\b",
                "\\bsubscription service(s)?\\b",
                "(manage|handle|process|provide)(.){0,64}(subscription)",
                "\\brecurring payments\\b",
            ],
            "CloudService": ["cloud(.){0,20}service"],
            "StorageService": [
                "storage(.){0,20}service",
                "\\bcloud storage\\b",
                "\\bstore(.){0,20}data\\b",
            ],
            "BackupService": ["backup(.){0,20}service"],
            "MusicService": ["music(.){0,20}service"],
            "ThemeService": ["theme(.){0,20}service"],
            "WallpaperService": ["wallpaper(.){0,20}service"],
            "LocationService": ["location(.){0,20}service", "\\bmap navigation"],
            "WeatherService": [
                "weather(.){0,20}service",
                "(retrieve|retrieving) weather",
            ],
            "SecurityService": ["security(.){0,32}service"],
            "CommunicationService": ["communication(.){0,32}service"],
            "HeatingSystem": [
                "\\bheating(.){0,64}system",
                "(adjust)(.){0,20}(temperature|thermostat)",
            ],
            "CoolingSystem": [
                "\\bcooling(.){0,64}system",
                "\\bair(-| )condition(ing)?(.){0,20}system\\b",
            ],
            "Navigation": ["\\bmap navigation"],
            "FindDevice": ["\\bfind(ing)?(.){0,20}device\\b"],
            "ConserveResources": ["conserve resource"],
            "SaveWater": ["\\b(sav|conserv)(e|ing) water\\b"],
            "SaveEnergy": ["\\b(sav|conserv)(e|ing) energy\\b"],
            "OptimizeWifFi": ["(optimize|improve)(.){0,20}wi(-)?fi"],
            "SwitchLight": [
                "turn (off|on)(.){0,20}light",
                "\\bswitch(ing)?(.){0,32}light(s)?\\b",
            ],
            "Invoice": [
                "\\b(issue|provide|generate|send|deliver)(.){0,32}(invoice|bill)(s)?\\b"
            ],
            "SocialSharing": ["\\bsocial shar(e|ing)\\b"],
            "ErrorDiagnosis": [
                "(diagnose|diagnosis)(.){0,32}(error|problem|issue|fault|failure)"
            ],
            "PhotoMetadata": [
                "(store|embed|add|save|record)(.){0,32}(metadata|geotag|tag|information|detail)(.){0,32}(photo|image|picture)",
                "record(.){0,20}(while|when|during)(.){0,20}(tak|captur)(e|ing)(.){0,20}(photo|image|picture)",
            ],
            "SecurityScan": ["security scan function(s)?"],
            "VoiceSupport": [
                "voice enabled (device|product|service|feature)",
                "\\bvoice support",
            ],
            "TaxFreePurchase": [
                "(?=.*(provide|enable|allow|make possible))(?=.*tax-free)"
            ],
            "ScanQRCode": ["(scan)(.){0,64}qr(-| )code"],
            "SaveToAlbum": ["(save|store)(.){0,64}album"],
            "DeliverPrize": [
                "(provide|send|ship|deliver)(.){0,64}(winnings|prize|trophy)"
            ],
            "EnablingConnectivity": ["\\benabl(e|ing) connectivity", "work together"],
            "ParkDevice": ["\\b(park)(.){0,32}(device|product|mower|vacuum|robot)"],
            "DataInfrastructure": ["(provide|run|maintain)(.){0,32}infrastructure"],
            "GoogleAssistance": ["\\bgoogle assistant\\b"],
            "AmazonAlexa": ["\\bamazon alexa\\b"],
            "AppleSiri": ["\\bapple siri\\b"],
        }
    ),
    communication=AttributePattern.from_dict(
        {
            "InformationalUpdates": [
                "\\b(keep|send)(ing)? you (inform|update|posted)",
                "\\b(email|message)(s)?(.){0,32}contain(ing)? (the )?information\\b",
                "\\b(send(ing)?|provid(e|ing)|receiv(e|ing))(.){0,32}(news|information|details|notice)",
                "\\bnew(.){0,32}(information|update|detail)(s)?\\b",
                "\\b(change|update)(s)?(.){0,32}(service|feature|product)(s)?\\b",
                "\\binformation about (how|when|what|where|why)\\b",
            ],
            "Notifications": [
                "\\b(push-)?notification(s)?\\b",
                "\\balert(s)?\\b",
                "\\bnotify(ing)?\\b",
                "\\btell you (when|if)\\b",
                "\\bpush message(s)?\\b",
            ],
            "DowntimeNotifications": [
                "\\bdowntime (alert|notification)(s)?\\b",
                "\\bnotify(ing)? you (about|of)(.){0,32}downtime\\b",
            ],
            "MandatorySystemNotifications": [
                "mandatory (service|system) notification(s)?"
            ],
            "Reminders": ["\\breminder(s)?\\b", "\\bremind you\\b"],
            "Feedback": [
                "\\bfeedback\\b",
                "\\bsuggestion(s)?\\b",
                "(obtaining|gather)(.){0,20} (view|opinion)(s)?",
            ],
            "Review": ["\\breview(s)?\\b", "\\brat(ed|ing)?\\b"],
            "Newsletter": ["\\bnewsletter(s)?\\b", "\\bnews bulletin\\b"],
            "Survey": ["\\bsurvey(s)?\\b", "\\bquestionnaire(s)?\\b"],
            "CustomerService": [
                "\\bcustomer (service|support)\\b",
                "provid(e|ing)(.){0,32}(support|assistance|help|solution(s)?)\\b",
                "receiv(e|ing) advice\\b",
                "\\b(process(ing)?|verify) (your|the )?(request|issue|problem|query|queries)\\b",
                "\\bcontact form\\b",
                "\\b(solve|answer|respond|handl(e|ing)|deal(ing)?)(.){0,32}(enquirie|question|query|queries|issue|request)(s)?\\b",
                "support communication",
                "call(-| )?centre(s)?\\b",
                "\\bhelp desk\\b",
                "support (purpose|request|issue|question)(s)?\\b",
                "\\b(grant|deny)(.){0,20}request",
                "\\bproduct support\\b",
            ],
            "TechnicalSupport": [
                "\\btechnical support\\b",
                "\\btech support\\b",
                "\\btechnical help\\b",
                "\\btroubleshoot (any |your )?(problem|issue)(s)?\\b",
            ],
            "ChatBot": ["\\bchat(-)?bot\\b", "\\bvirtual assistant\\b"],
            "LiveChat": ["\\blive chat\\b", "\\breal[- ]time chat\\b"],
            "AccountVerification": [
                "\\baccount verif(y|ication)(s)?\\b",
                "\\bconfirm(.){0,20}creation(.){0,20}account",
            ],
            "OrderCommunication": [
                "\\b(order|shipping) (confirmation|notification)(s)?\\b",
                "\\bconfirm(ing)?(.){0,20}order(s)?\\b",
                "(detail|information|message|notification|alert|notice)(s)?(.){0,20}about( your)? order",
                "(informing|notify)(.){0,48}(order|shipping)\\b",
                "(?=.*\\breturn\\b)(?=.*(instruction|detail|information))",
                "communicati(ng|ion)(.){0,32}(order|shipping|delivery)",
                "\\bquestion(s)? about (your )?order(s)?\\b",
            ],
            "BillingInquiries": [
                "\\b(billing|invoice|payment)( )?(inquiry|question|issue|problem)(s)?\\b",
                "\\b(question|issue|problem)(s)? about (your )?(bill|invoice|payment)\\b",
            ],
            "PricingInquiries": [
                "\\b(pricing|cost|price)( )?(inquiry|question|issue|problem)(s)?\\b",
                "\\b(question|issue|problem)(s)? about (your )?(pricing|cost|price)\\b",
            ],
            "LegalChanges": [
                "\\b(?=.*(change|update))(?=.*(terms|conditions|(privacy|security) (policy|notice)|legal|agreement))",
                "\\bprivacy update(s)?\\b",
            ],
            "WinnerNotification": [
                "\\b(notify|inform)(.){0,32}(winner|won|participant)\\b"
            ],
            "MarketingMessage": [
                "\\b(promotional|marketing) (text|message|offer|e(-)?mail|sms|communication)(s)?\\b",
                "(?=.*(contact|message|e(-)?mail))(?=.*interested in)",
                "(?=.*(send|receive))(?=.*(brochure|catalog|catalogue))",
                "(?=.*(e(-)?mail|sms))(?=.*campaign)",
            ],
            "SocialMedia": [
                "\\bfan page(s)?\\b",
                "(via|using) social media",
                "community (platform|page|site|forum)",
                "company representation page",
            ],
            "ProductSafety": ["\\bsecurity alert(s)?\\b"],
            "EmergencyContact": ["(?=.*emergency)(?=.*(notify|contact|alert|reach))"],
            "ErrorReporting": [
                "(notif(i|y)|alert|report)(.){0,32}(error|issue|problem)(s)?",
                "(error|issue|problem)(s)?(.){0,32}(report|notif(i|y)|alert)",
            ],
            "TransactionCommunication": [
                "(?=.*(transaction|receipt|purchase))(?=.*(communication|message|notification|e(-)?mail|alert|detail|notice))"
            ],
            "BirthdayGreeting": ["(?=.*birthday)(?=.*(greeting|message))"],
            "Membership": [
                "(?=.*(membership|subscription))(?=.*(contact|communication|message|notification|e(-)?mail|alert|detail|notice))"
            ],
        }
    ),
    tech_priv=AttributePattern.from_dict(
        {
            "Anonymization": ["anonymization", "anonymised", "anonymized"],
            "Pseudonymization": ["pseudonymization", "pseudonymised", "pseudonymized"],
            "Aggregation": ["aggregation", "aggregated"],
            "Shortened": ["shortened", "truncated", "abbreviated"],
            "DataSeparation": [
                "(?=.*\\b(isolat|separat|segregat)\\w*)(?=.*\\b(personal(ly)?[\\s-]identifiable|pii|personal)\\s+(data|information))(?=.*\\b(non[\\s-]personal(ly)?[\\s-]identifiable|npii|non[\\s-]personal)\\s+(data|information))",
                "(?=.*\\b(keep|maintain|store|process)\\w*\\s+separate(ly|d)?)(?=.*\\b(personal|pii)\\b)(?=.*\\b(non-personal|npii)\\b)",
                "(?=.*\\b(not|never|cannot|will\\s+not|shall\\s+not)\\s+(merge|link|combine|connect|associate|join)\\w*)(?=.*\\b(personal|pii|pseudonymized|anonymized|de-identified))(?=.*\\b(data|information)\\b)",
                "(?=.*\\b(pseudonymized|pseudonymised|anonymized|anonymised|de-identified)\\s+(data|information))(?=.*\\b(not|never|cannot)\\s+(merge|link|re-identif))",
            ],
            "Desensitization": ["desensitization", "desensitized"],
        }
    ),
    tech_sec=AttributePattern.from_dict(
        {
            "Encryption": ["encrypt"],
            "Monitoring": ["monitoring", "monitored"],
            "TwoFactorAuth": [
                "(two|multi)(-| )factor authentication",
                "2fa",
                "two factor auth",
                "two-step verification",
                "two step verification",
            ],
            "HashedPassword": ["hashed password", "password hashing"],
        }
    ),
    cont_sec=AttributePattern.from_dict(
        {
            "DataProcessingAgreement": ["data processing agreement"],
            "StandardContractualClauses": ["standard contractual clauses", "\\bscc\\b"],
            "AdequacyDecision": ["adequacy decision"],
            "Audits": ["\\baudits\\b"],
            "Confidentiality": ["\\bconfidentiality\\b", "strictly confidential"],
            "BindingContractualRules": [
                "binding corporate rules",
                "binding contractual obligations",
            ],
        }
    ),
    chosen=AttributePattern.from_dict(
        {
            "AuthorizedAgent": [
                "(?=.*(authorized|authorization|designate))(?=.*\\b(agend|representative)(s)?\\b)",
                "authorized to act on your behalf",
                "authorize someone to act on your behalf",
                "legally authorized person",
            ],
            "DesignatedPerson": ["\\bperson you designate", "designated person"],
            "AppointedRepresentatives": ["(appointed) representative"],
            "Invitee": ["\\binvitee(s)?\\b"],
            "Proxy": ["proxy of the holder"],
            "LegalGuardian": ["\\blegal guardian(s)?\\b"],
            "AuthorizedUser": ["\\bauthorized user"],
            "TrustedIndividual": [
                "\\b(trusted|selected) (individual|person|contact)(s)?\\b"
            ],
        }
    ),
    profiling=AttributePattern.from_dict(
        {
            "NoProfiling": [
                "not performed",
                "not engage",
                "(not|other then)(.){0,64}(infer characteristics|profiling)",
                "no profile(.){0,32}(generated|created)",
                "not subject(ed)?to",
            ]
        }
    ),
    automated_decision=AttributePattern.from_dict(
        {
            "NotAutomatedDecisionMaking": [
                "not performed",
                "not engage",
                "(not|other then)(.){0,64}automated decision(-| )making",
                "no automated decision(-| )making",
                "not subject(ed)?to",
            ]
        }
    ),
)
""" English language attribute patterns. """

EN_DURATION_PATTERN_CONFIG: DurationPattern = DurationPattern(
    unit=AttributePattern.from_dict(
        {
            "Days": [r"\bday(s)?\b"],
            "Weeks": [r"\bweek(s)?\b"],
            "Months": [r"\bmonth(s)?\b"],
            "Years": [r"\byear(s)?\b"],
            "Hours": [r"\bhour(s)?\b"],
            "Minutes": [r"\bminute(s)?\b"],
            "Seconds": [r"\bsecond(s)?\b"],
        }
    ),
    length=AttributePattern.from_dict(
        {
            "1": [r"\b1\b", r"\bone\b"],
            "2": [r"\b2\b", r"\btwo\b"],
            "3": [r"\b3\b", r"\bthree\b"],
            "4": [r"\b4\b", r"\bfour\b"],
            "5": [r"\b5\b", r"\bfive\b"],
            "6": [r"\b6\b", r"\bsix\b"],
            "7": [r"\b7\b", r"\bseven\b"],
            "8": [r"\b8\b", r"\beight\b"],
            "9": [r"\b9\b", r"\bnine\b"],
            "10": [r"\b10\b", r"\bten\b"],
            "15": [r"\b15\b", r"\bfifteen\b"],
            "20": [r"\b20\b", r"\btwenty\b"],
            "30": [r"\b30\b", r"\bthirty\b"],
            "60": [r"\b60\b", r"\bsixty\b"],
            "90": [r"\b90\b", r"\bninety\b"],
            "180": [r"\b180\b", r"\bone[- ]?hundred (and )?eighty\b"],
            "365": [r"\b365\b", r"\bone[- ]?hundred (and )?sixty[- ]?five\b"],
        }
    ),
)
""" English language duration patterns. """

EN_DATE_PATTERN_CONFIG: DatePattern = DatePattern(
    {
        "%Y-%m-%d": "\\b(\\d{4})-(\\d{1,2})-(\\d{1,2})\\b",
        "%Y/%m/%d": "\\b(\\d{4})/(\\d{1,2})/(\\d{1,2})\\b",
        "%m/%d/%Y": "\\b(\\d{1,2})/(\\d{1,2})/(\\d{4})\\b",
        "%m-%d-%Y": "\\b(\\d{1,2})-(\\d{1,2})-(\\d{4})\\b",
        "%d.%m.%Y": "\\b(\\d{1,2})\\.(\\d{1,2})\\.(\\d{4})\\b",
        "%d/%m/%Y": "\\b(\\d{1,2})/(\\d{1,2})/(\\d{4})\\b",
        "%d-%m-%Y": "\\b(\\d{1,2})-(\\d{1,2})-(\\d{4})\\b",
        "%B %d, %Y": "\\b(January|February|March|April|May|June|July|August|September|October|November|December)\\s+(\\d{1,2}),?\\s+(\\d{4})\\b",
        "%d %B %Y": "\\b(\\d{1,2})\\s+(January|February|March|April|May|June|July|August|September|October|November|December)\\s+(\\d{4})\\b",
        "%b %d, %Y": "\\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s+(\\d{1,2}),?\\s+(\\d{4})\\b",
        "%d %b %Y": "\\b(\\d{1,2})\\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s+(\\d{4})\\b",
        "%m/%d/%y": "\\b(\\d{1,2})/(\\d{1,2})/(\\d{2})\\b",
        "%d.%m.%y": "\\b(\\d{1,2})\\.(\\d{1,2})\\.(\\d{2})\\b",
        "%Y%m%d": "\\b(\\d{4})(\\d{2})(\\d{2})\\b",
        "%B %Y": "\\b(January|February|March|April|May|June|July|August|September|October|November|December),?\\s+(\\d{4})\\b",
        "%b %Y": "\\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s*,?\\s+(\\d{4})\\b",
    }
)
""" English language date patterns. """
